import { createFileRoute, Link } from "@tanstack/react-router";
import { FileText, CalendarCheck, Search, ArrowRight, ShieldCheck } from "lucide-react";

import { AppShell } from "@/components/AppShell";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Northwork — AI Workplace Productivity Assistant" },
      {
        name: "description",
        content:
          "Turn meeting notes, task lists and research into clear, editable output with AI. Nothing is stored.",
      },
      { property: "og:title", content: "Northwork — AI Workplace Productivity Assistant" },
      {
        property: "og:description",
        content:
          "Meeting notes, task planning and research summaries generated by AI and fully editable.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Dashboard,
});

const TOOLS = [
  {
    to: "/meeting-notes",
    icon: FileText,
    title: "Meeting Notes AI",
    body: "Paste raw notes and get a summary, key points, action items, decisions and deadlines.",
  },
  {
    to: "/task-planner",
    icon: CalendarCheck,
    title: "AI Task Planner",
    body: "Enter tasks with priorities and deadlines to get a prioritised daily or weekly schedule.",
  },
  {
    to: "/research",
    icon: Search,
    title: "AI Research Assistant",
    body: "Give a topic, pasted text or an article link for insights, findings and recommendations.",
  },
] as const;

function Dashboard() {
  return (
    <AppShell
      title="Your AI workspace"
      description="Three focused assistants for the work that eats your day. Every result is editable, and nothing you enter leaves this session."
    >
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        {TOOLS.map(({ to, icon: Icon, title, body }) => (
          <Link key={to} to={to} className="group surface-panel flex flex-col gap-4 p-6">
            <span className="flex size-10 items-center justify-center rounded-lg bg-navy text-primary-foreground">
              <Icon className="size-5" />
            </span>
            <div>
              <h2 className="text-base font-semibold">{title}</h2>
              <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{body}</p>
            </div>
            <span className="mt-auto inline-flex items-center gap-1.5 text-sm font-medium text-navy">
              Open tool
              <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" />
            </span>
          </Link>
        ))}
      </div>

      <div className="mt-6 flex items-start gap-3 rounded-xl border border-border bg-card p-5">
        <ShieldCheck className="mt-0.5 size-5 shrink-0 text-navy" />
        <p className="text-sm leading-relaxed text-muted-foreground">
          No accounts, no database, no history. Your notes and AI results live only in this browser
          tab and disappear when you close or refresh it.
        </p>
      </div>
    </AppShell>
  );
}
